ALTER TABLE site ADD COLUMN street_type VARCHAR(50) NULL;
ALTER TABLE site ADD COLUMN category VARCHAR(100) NULL;
ALTER TABLE site ADD COLUMN in_service DATE NULL;
ALTER TABLE site ADD COLUMN county VARCHAR(100) NULL;
ALTER TABLE site ADD COLUMN jurisdiction VARCHAR(100) NULL;
ALTER TABLE site ADD COLUMN primary_purpose VARCHAR(255) NULL;
